name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create multi-node KinD cluster
        uses: arcalot/actions/kind@main
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install build tools
        run: python3 -m pip install --upgrade build
      - name: Test python build
        run: python3 -m build
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: dist
          if-no-files-found: error
      - name: Install test tools
        run: python3 -m pip install coverage
      - name: Install depedencies
        run: python3 -m pip install -r requirements.txt
      - name: Run unit tests
        run: python -m coverage run -a -m unittest discover -s tests -v
      - name: Collect coverage report
        run: |
          python -m coverage html
      - name: Publish coverage report to job summary
        run: |
          pip install html2text
          html2text --ignore-images --ignore-links -b 0 htmlcov/index.html >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: htmlcov
          if-no-files-found: error
      - name: Test build docker image
        run: docker-compose build
      - name: Run plugin
        run: docker-compose up
